name: CI (light)
on:
  push:
  pull_request:
jobs:
  pipeline-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Run ingest
        run: python src/ingest/ingest_local.py
      - name: Run transform
        run: python src/transform/flag_and_kpi.py
      - name: Verify outputs
        run: |
          test -f data/processed/transactions_enriched.csv
          test -f data/processed/kpi_by_country.csv
          test -f data/processed/kpi_by_channel.csv
          echo '✅ outputs found.'
